package in.rajlabs.buuker_backend.Buuker.Backend.dto;

import in.rajlabs.buuker_backend.Buuker.Backend.model.OrderStatus;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * Data Transfer Object for TransactionLedger.
 */
@Data
public class TransactionLedgerDTO {

    /**
     * Unique identifier for the transaction.
     * This is typically generated by the system and not provided by the client during creation.
     */
    private String transactionID;

    @NotNull(message = "Buy price is required")
    @Min(value = 0, message = "Buy price must be non-negative")
    private double buyPrice;

    @NotNull(message = "Final receive amount is required")
    @Min(value = 0, message = "Final receive amount must be non-negative")
    private double finalReceiveAmount;

    @NotNull(message = "Commission is required")
    @Min(value = 0, message = "Commission must be non-negative")
    private double commission;

    @NotNull(message = "Unit is required")
    @Min(value = 1, message = "Unit must be at least 1")
    private int unit;

    @NotBlank(message = "Merchant ID is required")
    private String merchantID;

    @NotBlank(message = "Customer ID is required")
    private String customerID;

    @NotBlank(message = "Booking platform is required")
    private String bookingPlatform;

    @NotBlank(message = "Booking mobile number is required")
    private String bookingMobNo;

    private String shippedFrom;

    private String shippingTrackingID;

//    @NotNull(message = "Running balance is required")
//    @Min(value = 0, message = "Running balance must be non-negative")
//    private double runningBalance; done at server Side

    /**
     * Epoch timestamp in milliseconds when the transaction was created.
     * Managed automatically by the system.
     */
    private Long createdOn;

    /**
     * Epoch timestamp in milliseconds when the transaction was last updated.
     * Managed automatically by the system.
     */
    private Long updatedOn;

    private boolean bookedViaCard;

    private String remark;

    @NotNull(message = "Order status is required")
    private OrderStatus orderStatus = OrderStatus.ORDERED;

    @NotBlank(message = "Product name is required")
    private String productName;

    private String productLink;
}
